---
- set_fact:
    # yamllint disable-line rule:line-length
    docker_container: '{{ django_container_defaults | combine(django_container )}}'

- include_tasks: ./common.yml
  vars:
    django_image: '{{ docker_container.image }}'


- name: Run collectstatic
  docker_container: >-
    {{ docker_container | combine({
      "name": "django-collectstatic",
      "command": "./manage.py collectstatic --no-input --clear",
      "detach": false,
      "restart_policy": "no",
      "ports": []
    })}}

- name: Run migrations
  run_once: true
  docker_container: >-
    {{ docker_container | combine({
      "name": "django-migrate",
      "command": "./manage.py migrate",
      "detach": false,
      "restart_policy": "no",
      "ports": []
    })}}

- name: Run Django app
  docker_container: '{{ docker_container }}'
