---
- name: Converge
  hosts: django
  vars:
    django_dir: /opt/my_app/
  tasks:
    - name: Install rsync
      delegate_to: localhost
      changed_when: false
      shell: rsync --version || (apt-get update && apt-get install rsync -y)

    - name: Copy example project
      synchronize:
        src: ../../django_example_project/
        dest: '{{ django_dir }}'

    - name: Install Django
      import_role:
        name: ansible-role-django
      vars:
        django_docker_container:
          command: >-
            gunicorn
            -b 0.0.0.0:80
            django_example_project.wsgi
          env:
            DJANGO_SECRET_KEY: very-secret
            DJANGO_STATIC_ROOT: /app/staticfiles
          ports:
            - '80:80'
