---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - &common
    name: web
    vpc_subnet_id: subnet-1efffb7b
    image: ami-0c48db26521ca9f07
    instance_type: m5.xlarge
  - <<: *common
    name: worker
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true
  inventory:
    group_vars:
      all:
        django_dir: /opt/my_app/
        django_celery_app: hello_app
        django_env:
          DJANGO_SECRET_KEY: very-secret
          DJANGO_STATIC_ROOT: /app/staticfiles
          CELERY_BROKER_URL: 'redis://{{ hostvars.web.ansible_default_ipv4.address }}:6379'
verifier:
  name: testinfra
  directory: ../../tests
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
